sudo: required
services:
  - docker

before_install:
  - docker build -t ramezwasfy91/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ramezwasfy91/react-test npm test

after_success:
  - docker build -t ramezwasfy91/prod-client -f ./client/Dockerfile ./client
  - docker build -t ramezwasfy91/prod-nginx -f ./nginx/Dockerfile ./nginx
  - docker build -t ramezwasfy91/prod-server -f ./server/Dockerfile ./server
  - docker build -t ramezwasfy91/prod-worker -f ./worker/Dockerfile ./worker
  # login to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push ramezwasfy91/prod-client
  - docker push ramezwasfy91/prod-nginx
  - docker push ramezwasfy91/prod-server
  - docker push ramezwasfy91/prod-worker


